Feature: Tick frequency is preserved in .circ file
logisim-evolution/logisim-evolution pull request #1006
Opened 2021-09-02 13:33 UTC by BFH-ktt1

(addresses #990)
Step1: the selected tick frequency is saved in the clock component in the .circ file

2021-09-02 15:08 UTC, BFH-ktt1 commented
@maehne, @MarcinOrlowski : I would opt to merge this feature still with 3.6.0, as it is very useful, but I also understand when you do not agree.

2021-09-02 21:07 UTC, maehne reviewed
Modifications to the source files look sensible to me. However, I think that they only partly address issue #990 and especially [my comment](https://github.com/logisim-evolution/logisim-evolution/issues/990#issuecomment-912045988) there.

2021-09-03 09:11 UTC, MarcinOrlowski requested changes

2021-09-03 09:11 UTC, MarcinOrlowski commented on src/main/java/com/cburch/logisim/file/XmlWriter.java
> +      final var a = doc.createElement("a");
No single letter vars. Please rename to i.e. `elementA` or so.

2021-09-03 09:11 UTC, MarcinOrlowski commented on src/main/java/com/cburch/logisim/file/XmlReader.java
> +              final var val = defaults.getDefaultAttributeValue(attr, ver);
`final var val` that's bit confusing. Mind replacing `val` with i.e. `attrVal`?

2021-09-03 15:26 UTC, BFH-ktt1 commented
removing this PR, as #1018 addresses all features requested.

2021-09-03 15:26 UTC, closed without merging