Corrected handling of ShadowJar filename for unstable versions
logisim-evolution/logisim-evolution pull request #1091
Opened 2021-09-13 18:30 UTC by MarcinOrlowski

2021-09-13 18:59 UTC, davidhutchens reviewed
I think there are still two problems. Both are related to the change in the name of the Windows .msi file. By changing the version used in createMsi, the jpackage output filename will also be changed to not have the "dev".

Since the version for the .msi no longer contains the "dev", the part of this .yml that grabs the result and makes it available needs to look for a name that does not contain the "dev".

The related problem is that in the build.gradle.kts file, gradle is looking for an output file for the createMsi task that has the "dev" in the name. Since jpackage isn't creating a file with that name, the build will not properly detect if it needs to run the task again.

2021-09-13 19:01 UTC, MarcinOrlowski commented
> Note that the Windows version will now not have the "dev" at all.

I am afraid there's nothing I can do about it. The `-dev` is still part of the version (i.e. `--version` or About dialog shall show it, but MSI won't.

2021-09-13 19:41 UTC, MarcinOrlowski commented
Good spot, David. Hope I addressed all this now. PTAL

2021-09-13 19:53 UTC, davidhutchens requested changes
My last paragraph was referring to: `outputs.file("${ext.get(TARGET_FILE_PATH_BASE) as String}.msi")` on line 335 of build.gradle.kts. It also assumes that the "dev" is in the output filename from jpackage.

2021-09-13 20:15 UTC, MarcinOrlowski commented
Third time's the charm... 🤞🏻 PTAL

2021-09-13 20:57 UTC, davidhutchens approved these changes
That looks good to me.

2021-09-13 21:24 UTC, maehne approved these changes
LGTM

2021-09-14 10:30 UTC, BFH-ktt1 approved these changes

2021-09-14 10:30 UTC, merged

2021-09-15 16:53 UTC, maehne reviewed
@MarcinOrlowski: I found two minor issues, which you may consider to fix.

2021-09-15 18:37 UTC, MarcinOrlowski commented on .github/workflows/nightly.yml
> +          # LSe version string can have additional "unstable" indicator (i.e. "-dev") but
Well, the `-` is easy-to-handle separator. But I think I can fix that in `LogisimVersion` class and make it  support hyphen-less form pretty cheap. Will address that soon.