Added command line argument --toplevel-circuit such that for -tty stat you can override the toplevel circuit in the project.
logisim-evolution/logisim-evolution pull request #1110
Opened 2021-09-18 07:06 UTC by BFH-ktt1

2021-09-18 09:06 UTC, MarcinOrlowski approved these changes

2021-09-18 14:44 UTC, BFH-ktt1 commented on src/main/resources/resources/logisim/strings/gui/gui_pl.properties
> +# ==> argMainCircuitOption =
done

2021-09-18 17:02 UTC, MarcinOrlowski requested changes

2021-09-18 17:02 UTC, MarcinOrlowski commented on src/main/java/com/cburch/logisim/gui/start/TtyInterface.java
> +    Circuit circuit;
What about simplification like this:

```java
    final var circuitToTest = args.getCircuitToTest();
    final var circuit = (circuitToTest == null || circuitToTest.length() == 0)
        ? file.getMainCircuit()
        : file.getCircuit(circuitToTest);
```

2021-09-19 07:17 UTC, BFH-ktt1 commented on src/main/java/com/cburch/logisim/gui/start/TtyInterface.java
> +    Circuit circuit;
done

2021-09-19 09:21 UTC, MarcinOrlowski approved these changes

2021-09-20 04:47 UTC, merged