Fix german translation
logisim-evolution/logisim-evolution pull request #1124
Opened 2021-09-25 15:33 UTC by Baumfinder

The name of the project was translated where it should not be translated

2021-09-25 16:31 UTC, MarcinOrlowski approved these changes

2021-09-25 16:32 UTC, MarcinOrlowski requested changes
Your PR must be forked from `develop` branch, not `master`

2021-09-26 08:19 UTC, BFH-ktt1 approved these changes

2021-09-26 11:43 UTC, closed without merging

2021-09-26 11:46 UTC, Baumfinder commented
I'll redo it the right way