Fixed German Translation
logisim-evolution/logisim-evolution pull request #1130
Opened 2021-09-26 16:58 UTC by Baumfinder

Name of Project was falsely translated

2021-09-26 17:03 UTC, MarcinOrlowski approved these changes

2021-09-26 17:07 UTC, MarcinOrlowski commented
I noticed there's another occurrence of `Logisim-Entwicklung` in project files (but not code). Can you fix that too?

2021-09-26 17:23 UTC, MarcinOrlowski requested changes
I noticed there's another occurrence of `Logisim-Entwicklung` in project files (in `src/main/resources/doc/de/html/guide/subcirc/sub-appear.html`). Can you update this PR and fix that too?

2021-09-27 12:28 UTC, Baumfinder commented
@MarcinOrlowski  Thanks for telling me, I've fixed that too.

2021-09-27 12:31 UTC, MarcinOrlowski requested changes

2021-09-27 12:31 UTC, MarcinOrlowski commented on src/main/resources/doc/de/html/guide/subcirc/sub-appear.html
> +        Es gibt vier Modelle für die grafische Darstellung der Schaltung (Logisim-evolution,Logisim-holycross,Klassisches-Logisim,Benutzerdefiniert). Die Version der Präsentation ist in der Eigenscha
May I also request adding single space after each `,` in `(Logisim-evolution,Logisim-holycross,Klassisches-Logisim,Benutzerdefiniert)` line?

2021-09-27 15:16 UTC, MarcinOrlowski approved these changes

2021-09-27 15:16 UTC, MarcinOrlowski commented
Thanks for correcting these issues.

2021-09-27 15:19 UTC, merged