Added limitations chapter to the docs
logisim-evolution/logisim-evolution pull request #1225
Opened 2021-10-11 06:36 UTC by MarcinOrlowski

Please let me know if I missed anything important or if this chapter should be rephrased for better clarity or anything.

2021-11-02 20:45 UTC, maehne commented
@MarcinOrlowski: Could you please address the feedback that we provided to your PR?

2021-11-03 00:11 UTC, MarcinOrlowski commented
@maehne Sure, I will fix whatever pending but that unfortunately most likely won't happen before the weekend as I am currently heavily occupied by other projects.

2021-11-03 09:50 UTC, maehne commented
@MarcinOrlowski: Thanks for the quick reply! No worries if it takes a while. We are also currently well occupied with other things.

2022-03-11 22:53 UTC, maehne requested changes
@MarcinOrlowski: Could you please address the changes requested to this PR, so that it can finally be merged? Thanks!

2022-08-23 16:07 UTC, maehne commented
@MarcinOrlowski: Could you please address the remaining review comments so that this PR can be merged in time for the upcoming version 3.8.0?

2022-08-23 16:15 UTC, MarcinOrlowski commented
@maehne Sorry, I was pretty busy recently. I will go by all pending reviews/tasks by end of the week. Is that OK?

2022-08-23 16:18 UTC, maehne commented
@MarcinOrlowski: If you manage to do it until the end of this week that would be great! Our target is to have a new release ready for the beginning of the autumn term mid September.

2022-08-30 05:49 UTC, MarcinOrlowski commented on docs/docs.md
> +  reality where phisical characteristics of each element can be different and affect their response time. Equalizing these times
Replaced confusing sentence with @maehne's.

2022-08-30 05:50 UTC, MarcinOrlowski commented on docs/docs.md
> +be aware about important limitations that may affect your works:
Changed.

2022-08-30 05:52 UTC, MarcinOrlowski commented on docs/docs.md
> +  therefore built-in library do not offer such elements, nor you will be able to contribute your own implementation as of today.
Made two sentences as I was unhappy with `;` separator. Not sure it's correct to start the sentence with `Therefore` though. @davidhutchens please correct if that's needed to be changed.

2022-08-30 05:53 UTC, MarcinOrlowski commented on docs/docs.md
> +
Added.

2022-08-30 18:33 UTC, davidhutchens approved these changes
This looks good to me. (And there is nothing wrong with starting a sentence with "Therefore,".)

Thanks for cleaning this up. I think it will help some users better understand what they can and cannot do.

2022-08-30 18:47 UTC, MarcinOrlowski commented
> And there is nothing wrong with starting a sentence with "Therefore,"

Thanks for the review and clarification. FYI: In some languages (i.e. Polish) it would look awkward (to natives) if you start the new sentence that way as usually you should go for compound sentence instead (hence my question).

2022-09-23 12:58 UTC, maehne approved these changes

2022-09-24 04:39 UTC, merged