(#1379) Removed custom appearance test from XML Writer's circuit serializer
logisim-evolution/logisim-evolution pull request #1380
Opened 2022-01-24 20:21 UTC by dbh201

### #1379 

In `XmlReader.java`, line 274, there was a test to determine whether a particular circuit had a custom appearance or the default. This function (`hasCustomAppearance()`) is implemented in `CircuitAppearance.java`, line 79.

The algorithm used for `hasCustomAppearance()` ignored pin count and position, among other things. If `hasCustomAppearance()` returned false for a circuit, then the `XmlReader` didn't write an `<appear>` block in the XML - which causes the next file load to erroneously reset the custom appearance of that circuit.

Instead of troubleshooting the algorithm, I opted to remove the test on line 274, since it doesn't seem to be very expensive to have an `<appear>` block for every circuit.

2022-01-25 09:31 UTC, maehne submitted a review, later dismissed
Looks good to me, but this needs to be reviewed by @BFH-ktt1 before merging, as he is much more familiar with this aspect of Logisim-evolution.

2022-01-25 10:38 UTC, BFH-ktt1 commented
@dbh201: As this is a solution to the problem I do not like it as the `.circ` file gets polluted with none required information (One of my previous PR's was exactly for the purpose to clean up the "pollution" inside the ".circ" file). I know where the problem comes from, as when you only change the rectangle or position of the pins, the function `hasCustomAppearance()` will return `false` just adding one extra object (for example a text) will fix the problem. If we want also the previous described behavior we have to adopt `hasCustomAppearance()` by checking the size of the rectangle and the positions of the pins.

2022-01-25 10:40 UTC, BFH-ktt1 requested changes
I do not like this "pollution" of the `.circ` file

2022-03-19 08:19 UTC, MarcinOrlowski commented
@BFH-ktt1 I suggest to reject this PR then for the reasons given above?

2022-08-05 16:32 UTC, BFH-ktt1 approved these changes

2022-08-05 16:32 UTC, merged