Added TTL 74245
logisim-evolution/logisim-evolution pull request #1466
Opened 2022-06-16 22:02 UTC by btb

split from #1461

2022-06-17 09:17 UTC, maehne requested changes
Looks mostly good to me!

As a side note: The TTL library lacks at the moment documentation. Help in this direction would be welcome, too.

2022-06-17 09:17 UTC, maehne commented on src/main/java/com/cburch/logisim/std/ttl/Ttl74245.java
> + * TTL 74x240 octal buffers and line drivers with three-state outputs
"74x240" -> "74x245"

2022-06-17 21:15 UTC, btb commented on src/main/java/com/cburch/logisim/std/ttl/Ttl74245.java
> + * TTL 74x240 octal buffers and line drivers with three-state outputs
fixed

2022-06-26 09:55 UTC, MarcinOrlowski approved these changes

2022-06-26 12:08 UTC, maehne approved these changes

2022-07-25 05:40 UTC, BFH-ktt1 approved these changes
Please fix the conflict

2022-08-05 16:03 UTC, BFH-ktt1 approved these changes

2022-08-05 16:03 UTC, merged