fix #1392
logisim-evolution/logisim-evolution pull request #1476
Opened 2022-07-14 23:03 UTC by R3dst0ne

2022-07-22 07:35 UTC, BFH-ktt1 requested changes

2022-07-22 07:35 UTC, BFH-ktt1 commented on src/main/java/com/cburch/logisim/std/ttl/Ttl74161.java
> +    long value = state.getValue().toLongValue();
final var ?

2022-07-22 12:21 UTC, R3dst0ne commented
Can someone, who is more familiar with the code, tell me whether my name ideas for `p` are correct?

2022-07-22 14:01 UTC, MarcinOrlowski commented
@R3dst0ne I peek the changed files and see just single change to `var`. All the remaining changes are logic changes and for me these are out of scope for this PR if you say it fixed #1392 because for me it looks it does not not that.

2022-07-22 16:14 UTC, R3dst0ne commented
@MarcinOrlowski
I should have labeled it more clearly.
It targets the things noted in [this](https://github.com/logisim-evolution/logisim-evolution/pull/1391#discussion_r813045331) comment (quoted in the description of #1392).

2022-08-05 16:38 UTC, BFH-ktt1 approved these changes

2022-08-05 16:46 UTC, merged