Develop
logisim-evolution/logisim-evolution pull request #1547
Opened 2022-09-25 20:27 UTC by BunchOfBits

Added a TTL model for the 74138 3 to 8 decoder

2022-09-25 20:59 UTC, maehne approved these changes
Except for two small casing issues, this PR looks good to me.

2022-09-25 20:59 UTC, maehne commented on src/main/java/com/cburch/logisim/std/ttl/Ttl74138.java
> + * This file is part of logisim-evolution.
Please use consistently "Logisim-evolution".

2022-09-25 20:59 UTC, maehne commented on src/main/java/com/cburch/logisim/std/ttl/Ttl74138.java
> + * with logisim-evolution. If not, see <http://www.gnu.org/licenses/>.
Please use consistently "Logisim-evolution".

2022-09-25 21:47 UTC, maehne approved these changes

2022-09-25 21:54 UTC, maehne requested changes
Please fix the code style issues reported by GitHub Actions.

2022-09-26 10:53 UTC, MarcinOrlowski commented
@BunchOfBits can you please assign an useful title to this PR please?

2022-09-26 13:13 UTC, BunchOfBits commented
> @BunchOfBits can you please assign an useful title to this PR please?

Done

2022-09-26 13:13 UTC, BunchOfBits commented
> Please fix the code style issues reported by GitHub Actions.

Done

2022-09-28 07:42 UTC, maehne approved these changes

2022-09-28 23:07 UTC, btb commented
duplicate of #1462 - either one should work fine.

2022-09-29 08:29 UTC, BunchOfBits commented
You are right, I just hadn't scrolled down the list of open PR's that far into the past (june 16th). I don't mind which one is accepted as long as one is accepted. This one has all checks green, while #1462 has still some red checks, so I think it would be easier to accept this one, but either one is fine by me.

2022-10-02 15:12 UTC, BFH-ktt1 commented
Closing as duplicate of #1462

2022-10-02 15:12 UTC, closed without merging