Corrected and updated developer docs
logisim-evolution/logisim-evolution pull request #1580
Opened 2022-11-05 18:32 UTC by MarcinOrlowski

@davidhutchens can you please take a look?

2022-11-05 20:07 UTC, davidhutchens requested changes
Here are my suggestions.

2022-11-05 20:40 UTC, MarcinOrlowski commented on docs/developers.md
> +  copy of `Logisim-evolution` repository on your own Github account.
Done.

2022-11-05 21:13 UTC, MarcinOrlowski commented on docs/developers.md
> +  ensure you checkout it before you create own branch
Done

2022-11-05 21:14 UTC, MarcinOrlowski commented on docs/style.md
> +* Some rules should be disabled, so we also ship `checkstyle-suppressions.xml` config file. It
Fixed.

2022-11-05 21:16 UTC, MarcinOrlowski commented on docs/style.md
> +  necessary to do anything extra to make it used.
Fixed.

2022-11-05 21:16 UTC, MarcinOrlowski commented on docs/style.md
> +    then set its value `checksyle-suppressions.xml` and click `Next.
Fixed.

2022-11-05 21:16 UTC, MarcinOrlowski commented on docs/style.md
> +    necessary to do anything extra to make it used. If for any reason you need that changed,
Done.

2022-11-05 21:18 UTC, MarcinOrlowski commented
Thanks @davidhutchens.  Corrected all issues you spotted. PTAL.

2022-11-05 21:22 UTC, davidhutchens approved these changes
This looks good to me.

2022-11-06 22:09 UTC, maehne approved these changes
Looks good to me. At some point, we may consider to document how to use Checkstyle also in other IDEs, e.g., VS Code.

2022-11-06 22:13 UTC, maehne commented
It might be also worth mentioning that it is common to create a branch for a topical fix/feature, which you then use to create the PR onto `develop`. Thus, the fix/feature can be easily evolved based on the review while also easing rebasing the branch or merging in changes to `develop` to keep in sync with upstream. Thus, a contributor can work easily on different topics in parallel without needing to wait that his PR gets merged upstream.

2022-11-07 08:12 UTC, merged