[snap] add desktop launcher, fixes #1662
logisim-evolution/logisim-evolution pull request #1701
Opened 2023-04-01 07:10 UTC by seanpquinn

This should add a launcher shortcut to Ubuntu.

Did a local snap build/install and noted the icon appeared

2023-04-01 10:47 UTC, MarcinOrlowski requested changes
Thanks for the patch. Please add `CHANGELOG` entry too like "Fixed appearance of LSe desktop icon [#1662]" or something like that.

2023-04-03 00:33 UTC, R3dst0ne commented on snap/gui/logisim-evolution.desktop
> +Name=Logisim Evolution
Please use the correct name: Logisim-evolution

2023-04-04 09:45 UTC, maehne requested changes
@seanpquinn: Thanks for looking into this issue. Please address the requested changes and then it looks good to me for merging.

2023-04-04 12:38 UTC, davidhutchens commented on snap/gui/logisim-evolution.desktop
> +Comment=Logisim-evolution is educational software for designing and simulating digital logic circuits.
@maehne: Is adding the "an" British English? I would not put it there, which is why it isn't in the README.me. At least in the U.S., software is a collective noun like flour or dirt. They are not used with "a" or "an".

2023-04-04 12:41 UTC, maehne commented on snap/gui/logisim-evolution.desktop
> +Comment=Logisim-evolution is educational software for designing and simulating digital logic circuits.
@davidhutchens: Thanks for your feedback as a native speaker! So, it can stay as is.

2023-04-05 04:20 UTC, seanpquinn commented on CHANGES.md
> +  * Fixed appearance of LSe desktop icon [#1662]
True, updated

2023-04-05 17:16 UTC, maehne approved these changes
@seanpquinn: Thanks!

2023-04-07 01:32 UTC, seanpquinn commented
Sorry, conflict resolution dismissed review? 😞

2023-04-07 19:22 UTC, maehne approved these changes

2023-04-07 19:24 UTC, maehne commented
@MarcinOrlowski: Please confirm that your feedback has been addressed.

2023-04-15 16:22 UTC, closed without merging