[ControlledBuffer] fix logic, closes #1642
logisim-evolution/logisim-evolution pull request #1704
Opened 2023-04-02 21:19 UTC by seanpquinn

- The TRUE inversion case had a bug that failed for ERROR and UNKNOWN types, removed confusing comment
- Changed ERROR branch to only handle error, not ERROR || UNKNOWN
- Updated documentation truth table to agree with the behavior described in the text

# Test plan
I looked at all input permutations, and observed behavior now matches the documentation: [test_controlled_buff_fix.zip](https://github.com/logisim-evolution/logisim-evolution/files/11133310/test_controlled_buff_fix.zip)

![image](https://user-images.githubusercontent.com/8419070/229378201-d02fa178-e670-4937-8b51-bd5ebddf0a8c.png)

![image](https://user-images.githubusercontent.com/8419070/229378219-278110be-f09d-4da0-87e4-71e5f38baa95.png)

2023-04-02 22:48 UTC, R3dst0ne commented
Please add this change to [CHANGES.md](https://github.com/logisim-evolution/logisim-evolution/blob/develop/CHANGES.md).

2023-04-04 10:02 UTC, maehne requested changes
@seanpquinn: Thanks for addressing this issue. Only some additional details should be fixed befor this can be merged. I agree with @R3dst0ne that this fix should be added to `CHANGES.md`.

@BFH-ktt1: It would be good if you could also have a look.

2023-04-06 05:12 UTC, seanpquinn commented on src/main/java/com/cburch/logisim/std/gates/ControlledBuffer.java
> +        state.setPort(0, isInverter ? in.not() : in.not().not(), GateAttributes.DELAY);
Sounds good. I removed the comment originally: found it a little confusing, but put it back as I worried about breaking the simulator.

2023-04-07 19:33 UTC, maehne approved these changes
@seanpquinn: Thanks for addressing my feedback! Looks good to me now. However, @BFH-ktt1 should have a second look and decide whether this behavioural change is OK with him, too.

2023-04-11 16:25 UTC, merged