Fixed mispositioned select/enable pins on Multiplexer
logisim-evolution/logisim-evolution pull request #1734
Opened 2023-04-25 03:46 UTC by xarkenz

New pull request for issue #1733.

My guess was essentially spot-on. The select port on the Multiplexer now only adjusts for Narrow size when the number of inputs is greater than 2.

Before:
![before image](https://user-images.githubusercontent.com/46010001/234169506-4329e6e8-b3d8-4111-9d0f-2e14c0487071.png)
After:
![after image](https://user-images.githubusercontent.com/46010001/234169563-9d884963-5d35-4491-997a-cb207eada124.png)

2023-04-25 03:57 UTC, xarkenz commented
Something I mentioned in the issue is that this change *technically* isn't backwards-compatible... so perhaps that's something to consider. It is small and fixes what is clearly a bug, though.

2023-04-25 08:42 UTC, maehne approved these changes
I am in favour to fix this bug, despite it may break some existing `.circ` files. The pin placement is obviously inconsistent.

2023-04-25 12:17 UTC, davidhutchens requested changes
I agree that this should be fixed.

I also think it should be mentioned in CHANGES.md to alert any users that they may need to adjust their circuits. Please add a line for this change.

Thank you for the bug report and the fix.

2023-04-25 17:26 UTC, davidhutchens approved these changes
Thank you. This looks good to me.

2023-04-26 10:47 UTC, maehne approved these changes

2023-04-26 10:54 UTC, merged