Update build.gradle.kts
logisim-evolution/logisim-evolution pull request #1749
Opened 2023-05-13 17:49 UTC by Ramseyxlil

2023-05-13 18:18 UTC, davidhutchens requested changes
I don't understand the purpose of this PR. Please provide more information if there is an actual purpose. Otherwise, I would recommend closing without merging.

2023-05-13 18:18 UTC, davidhutchens commented on build.gradle.kts
> -
I don't see the point in removing this line.

2023-05-14 21:36 UTC, MarcinOrlowski commented
I think there's no purpose here. It's just a garbage PR which should be rejected. OP should have no problem sending new PR if there's any contribution he tried but failed to provide (yet his for indicates no work).

2023-05-18 11:55 UTC, BFH-ktt1 commented
Closing this PR as no contribution

2023-05-18 11:55 UTC, closed without merging