Fixes #1747
logisim-evolution/logisim-evolution pull request #1824
Opened 2023-08-13 23:10 UTC by figurantpp

This pull request contains simple fixes for the problem described in issue #1747. The main culpirit was the fact that that the code did not discern between error addresses and not fully specified addresses. This also contains a small refactoring of the repeated calls to `state.setPort(RamAppearance.getDataOutIndex(0, attrs), Value.createError(dataBits), DELAY);` to a separate function for the sake of readability.

2023-08-14 04:37 UTC, BFH-ktt1 approved these changes
Looks good to me

2023-08-14 05:04 UTC, BFH-ktt1 requested changes
Could you please fix the code style error?

2023-08-14 11:10 UTC, figurantpp commented
> Could you please fix the code style error?

Of course!

2023-08-14 20:36 UTC, figurantpp commented
Done

2023-08-14 22:10 UTC, maehne approved these changes
Looks good to me!

2023-08-15 04:16 UTC, BFH-ktt1 approved these changes

2023-08-15 04:19 UTC, merged