Adding 16 bit float support
logisim-evolution/logisim-evolution pull request #1878
Opened 2023-09-27 18:12 UTC by aplq

This is done by converting all 16 bit floats to 32 bit then back to 16 bit. Conversion functions were validated against `Float.float16ToFloat()` and `Float.floatToFloat16()` available in Java 20 and later. In the future if updated to use Java 20 or newer would recommend switching to built in functions.
This relates to #1610 
Attached is the conversion validation file, which only runs in Java 20 or newer. I am not sure if there is a better way to store it or if it is even needed.
[Main.txt](https://github.com/logisim-evolution/logisim-evolution/files/12741860/Main.txt)

2023-09-28 07:35 UTC, maehne requested changes
Thanks for your contribution! Please add JavaDoc TODO comments to mark places, where the native conversion functions can be added / custom implementation can be removed. Also, please add a space after `//` to match the comment style in the remainder of the file. Use `var` and `final` where appropriate to not counter refactoring efforts by @MarcinOrlowski.

2023-09-28 07:35 UTC, maehne commented on src/main/java/com/cburch/logisim/data/Value.java
> +    if (oldExp == 0b11111 && oldFraction != 0)out |= 0x0400000;
Add space after closing `)`.

2023-10-02 00:05 UTC, aplq commented on src/main/java/com/cburch/logisim/data/Value.java
> +    if (oldExp == 0b11111 && oldFraction != 0)out |= 0x0400000;
Corrected in commit 0492178

2023-10-02 12:43 UTC, maehne submitted a review, later dismissed
Thanks @aplq for taking into account my feedback. Looks good to me!

2023-10-02 17:50 UTC, aplq commented
I forgot to note the addition in the change log. That is the only change made with the last commit (148af5b).

2023-10-02 20:36 UTC, maehne approved these changes

2023-10-03 04:35 UTC, merged