Update gui_de.properties
logisim-evolution/logisim-evolution pull request #1882
Opened 2023-09-28 12:18 UTC by Benni76

german language grammar error fixed

2023-10-02 12:59 UTC, maehne requested changes
Thanks for noticing the typo and proposing fixes!

2023-10-02 12:59 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_de.properties
> +simUnknownCharTitle = Zeichen für unbekannte Werte:
"Zeichen für unbekannten Wert:"

2023-10-02 12:59 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_de.properties
> +simUnknownColTitle = Farbe für unbekannte:
"Farbe für unbekannten Wert:"

2023-10-02 14:33 UTC, Benni76 commented on src/main/resources/resources/logisim/strings/gui/gui_de.properties
> +simUnknownCharTitle = Zeichen für unbekannte Werte:
Fixed

2023-10-02 14:34 UTC, Benni76 commented on src/main/resources/resources/logisim/strings/gui/gui_de.properties
> +simUnknownColTitle = Farbe für unbekannte:
Fixed

2024-08-16 12:43 UTC, maehne commented
We need to check for potential conflicts to PR #1870, i.e., merge this one after it.

2024-08-16 12:45 UTC, maehne approved these changes
Looks mostly good except for one translation.

2024-08-16 12:45 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_de.properties
> +simDefaultColors = Logisim-evolution standard Farben
"standard Farben" -> "Standardfarben"

2024-11-18 06:53 UTC, merged