Add autosave feature
logisim-evolution/logisim-evolution pull request #1965
Opened 2024-02-17 10:02 UTC by superenginegit

This PR is for the feature request of issue #1926.

**What I implemented:**
- Settings for autosaves: Autosaving can be toggled on or off and the time interval between two autosaves can be set.
- Creation of autosaves: Autosaving is performed regularly, but a new autosave will only be created if there were changes since the last autosave. Autosaves will be made for files that have been saved, for those they will be created in the same location as the original file. Autosave for files that have never be saved will be created in the users home directory.
- Autosaves that have been created for unsaved files will be checked for on start of logisim. And they can then be saved.
- Autosaves for saved files will be checked when that file is reopened. It can then be restored or deleted.

2024-02-22 10:14 UTC, maehne requested changes
Thanks for implementing this useful feature! It looks mostly good for me, but as this modifies some quite sensitive parts of the code, it should be at least also reviewed by @BFH-ktt1. It would be nice if you could add the newly introduced localisation strings to alls supported languages as placeholders at least. This facilitates additional translations.

2024-02-22 10:14 UTC, maehne commented on src/main/java/com/cburch/logisim/file/Loader.java
> +          DateTimeFormatter.ofPattern("yyyy-MM-dd_HH:mm:ss").format(LocalDateTime.now());
`:` in file names are not universally allowed, e.g., Windows doesn't allow them. Personally, I would opt to use `yyyyMMddHHmmss`, which also enables chronological sorting.

2024-02-22 10:14 UTC, maehne commented on src/main/java/com/cburch/logisim/file/Loader.java
> +   * @return True if writing was successfull, else false;
Typo: "successfull" -> "successful"

2024-02-22 10:14 UTC, maehne commented on src/main/java/com/cburch/logisim/file/LogisimFile.java
> +        autosaveLoading = true; // also set this to true to remember an autosave was loaded
"also" -> "Also" to be consistent with casing in other comments?

2024-02-22 10:14 UTC, maehne commented on src/main/resources/resources/logisim/strings/file/file.properties
> +autosaveError = Failed to create autosave for file: '%s'. Will not try again for this File until after a restart.
"File" -> "file"

2024-02-22 13:52 UTC, superenginegit commented
Thanks for the review, I have now added translation placeholders to the languages and fixed the other things you mentioned as well.

2024-02-22 14:16 UTC, maehne requested changes
Thanks for taking into account my review comments! I suggest some further improvements to the translations.

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/file/file_fr.properties
> +# ==> autosaveError = Failed to create autosave for file: '%s'. Will not try again for this file until after a restart.
"Échec de la création d'une sauvegarde automatique pour le fichier : '%s'. La tentative ne sera pas renouvelée pour ce fichier avant un redémarrage."

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/file/file_fr.properties
> +# ==> titleHandleAutosave = Autosave found
"Sauvegarde automatique trouvée"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/file/file_fr.properties
> +# ==> contentHandleAutosave = Autosave for file '%s' found. What should be done?
"Sauvegarde automatique pour le fichier '%s' trouvée. Que faut-il faire ?"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/file/file_fr.properties
> +# ==> loadOption = Load
"Charger"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/file/file_fr.properties
> +# ==> discardOption = discard
"Écarter"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/file/file_nl.properties
@BFH-ktt1: Maybe you could provide translations for these strings?

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_fr.properties
> +# ==> autosaveEnabled = Enable autosaving (Takes effect after a restart).
"Activer la sauvegarde automatique (prend effet après un redémarrage)."

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_fr.properties
> +# ==> autosaveInterval = Autosaving interval in seconds:
"Intervalle de sauvegarde automatique en secondes :"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_fr.properties
> +# ==> autosaveTitle = Autosave
"Sauvegarde automatique"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_fr.properties
> +# ==> autosaveHelp = Select autosave settings
"Sélectionner les paramètres de sauvegarde automatique"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_fr.properties
> +# ==> saveAndLoadOption = Save and load
"Sauvegarder et charger"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_fr.properties
> +# ==> titleHandleAutosave = Autosave found
"Sauvegarde automatique trouvée"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_fr.properties
> +# ==> contentHandleAutosave = Autosave file '%s' found. What should be done?
"Fichier de sauvegarde automatique '%s' trouvé. Que faut-il faire ?"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/file/file_de.properties
> +autosaveError = Erstellen der Autospeicherung für Datei '%s' fehlgeschlagen. Wird bis zum Neustart nicht wiederholt.
"Automatische Sicherung für Datei konnte nicht erstellt werden: '%s'. Wird erst nach einem Neustart erneut für diese Datei versucht."

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/file/file_de.properties
> +titleHandleAutosave = Autospeicherung gefunden
"Automatische Sicherung gefunden"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/file/file_de.properties
> +contentHandleAutosave = Autospeicherung für Datei '%s' gefunden. Wie vorgehen?
Automatische Sicherung für Datei '%s' gefunden. Wie vorgehen?

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_de.properties
> +autosaveEnabled = Aktiviere Autospeicherungen (Erfordert Neustart).
Aktiviere automatische Sicherungen (erfordert Neustart).

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_de.properties
> +autosaveTitle = Autospeichern
"Automatische Sicherungen"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_de.properties
> +autosaveHelp = Autospeicherungseinstellungen ündern
"Einstellungen für die automatischen Sicherungen ändern"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_de.properties
> +titleHandleAutosave = Autospeicherung gefunden
"Automatische Sicherung gefunden"

2024-02-22 14:16 UTC, maehne commented on src/main/resources/resources/logisim/strings/gui/gui_de.properties
> +contentHandleAutosave = Autospeicherungsdatei '%s' gefunden. Wie vorgehen?
Automatische Sicherungsdatei '%s' gefunden. Wie vorgehen?

2024-02-22 19:51 UTC, davidhutchens reviewed
I looked through the code and ran some tests to see how this worked. It looks good to me. Thank you for this contribution. I have one small request.

Would you please add a line to CHANGES.md to note the addition of an autosave feature?

2024-02-23 08:17 UTC, superenginegit commented
I've implemented the translation strings you've provided. And I've also added a line to the changes file noting the addition of autosaves. Thanks for your feedback!

2024-02-23 16:38 UTC, maehne approved these changes
From my side this PR is ready for merging. Unless @BFH-ktt1 would still like to provide Dutch localization strings.

2024-02-27 05:11 UTC, merged