Added the ability to change the colour of icons
logisim-evolution/logisim-evolution pull request #2017
Opened 2024-06-15 00:53 UTC by AlphaFromOmega

Affects all unicoloured icon draws and some multicoloured icons as well as replacing some of the GIF icons with paint icon functions. Fixes #641 
![example_dark_icons](https://github.com/logisim-evolution/logisim-evolution/assets/46257916/e2143c0c-3a63-4cf7-9ef8-0425f2c1f039)
![example_light_icons](https://github.com/logisim-evolution/logisim-evolution/assets/46257916/2800b80b-946c-4add-b482-8e16059525f5)

2024-06-15 01:53 UTC, davidhutchens requested changes
Thank you for the contribution.

Please fix the code style.

We do not use the * operator with imports. List the specific things you need.

The if should have the { at the end of the line. The else should have both } and { on the line with the else as in "} else {"

Normal code indentation should be 2 spaces. Wrapped lines should be indented 4 spaces.

Operators should have a space on either side.

2024-06-18 17:38 UTC, davidhutchens reviewed
I noted one more style change for a wrapped line. With that, this looks good to me.

But I don't use dark mode and so I'm not sure if it works well or if it should close issue #641. @maehne do you have thoughts here?

2024-06-18 17:38 UTC, davidhutchens commented on src/main/java/com/cburch/logisim/prefs/AppPreferences.java
> +          create(new PrefMonitorInt("componentIconColor", DEFAULT_COMPONENT_ICON_COLOR));
A wrapped line should be indented 4 characters. That would also make it match the line above.

2024-06-22 00:42 UTC, davidhutchens approved these changes
This looks good to me.

2024-06-22 15:43 UTC, maehne approved these changes
Looks good to me, too. Are the GIFs still used somewhere else? E.g., in the documentation? Otherwise, we could consider removing them.

2024-06-26 05:02 UTC, merged