Telnet improvements
logisim-evolution/logisim-evolution pull request #2118
Opened 2024-12-30 23:16 UTC by juli-99

This PR adds tips for the ports on the telnet component.
The max buffer size (256) was smaller than the default (1024). This got fixed as well.
Added the component to `CHANGES.md`

2024-12-31 07:41 UTC, maehne requested changes
Thanks for the improvements! Please fix the indicated minor issues!

2024-12-31 07:41 UTC, maehne commented on src/main/resources/resources/logisim/strings/std/std.properties
> +telnetOutTip = Output: reaseaved data
Typo: "received"

2024-12-31 07:41 UTC, maehne commented on src/main/resources/resources/logisim/strings/std/std_de.properties
> +telnetInTip = Eingang: Daten zu senden
zu sendende Daten

2024-12-31 07:41 UTC, maehne commented on src/main/resources/resources/logisim/strings/std/std_de.properties
> +telnetAvailableTip = Verfügbarkeit: Daten zum lesen verfügbar
Typo: "Lesen"

2024-12-31 07:41 UTC, maehne commented on src/main/resources/resources/logisim/strings/std/std.properties
> +telnetClkTip = Clock: send/receive data on trigger
"trigger" -> "clock edge"

2024-12-31 07:41 UTC, maehne commented on src/main/resources/resources/logisim/strings/std/std_de.properties
> +telnetModeAttr = Verwende Telnet Protokoll
"Telnet-Protokoll"

2024-12-31 07:41 UTC, maehne commented on src/main/resources/resources/logisim/strings/std/std_de.properties
> +telnetClkTip = Takt: bei Triggersignal Daten lesen/senden
"Triggersignal" -> "Taktflanke"

2025-01-01 22:36 UTC, juli-99 commented on src/main/resources/resources/logisim/strings/std/std_de.properties
> +telnetClkTip = Takt: bei Triggersignal Daten lesen/senden
"Triggersignal" gets used multiple times in the German translation for the std components. "Takt Flanke" currently only gets used once.

2025-01-02 08:28 UTC, maehne requested changes
Thanks for taking into account my feedback! Looking at the German localization, I think "Lesen" and "Senden" need to start with a capital letter, as they are used as a noun in the respective context. The rest looks OK to me.

2025-01-02 08:28 UTC, maehne commented on src/main/resources/resources/logisim/strings/std/std_de.properties
> +telnetClkTip = Takt: bei Triggersignal Daten lesen/senden
I agree with remaining consistent.

2025-01-02 08:28 UTC, maehne commented on src/main/resources/resources/logisim/strings/std/std_de.properties
> +telnetWriteTip = lesen aktivieren
"Lesen"

2025-01-02 08:28 UTC, maehne commented on src/main/resources/resources/logisim/strings/std/std_de.properties
> +telnetReadTip = senden aktivieren
"Senden"

2025-01-03 07:17 UTC, maehne approved these changes
Thanks!

2025-01-05 09:45 UTC, merged

2025-01-06 23:28 UTC, zdimension commented
@juli-99 thanks for your PR! Good catch on the max buffer size being smaller than default. Good idea to add tooltips!