Fixed missing port on DotMatrix
logisim-evolution/logisim-evolution pull request #621
Opened 2021-06-05 19:12 UTC by R3dst0ne

DotMatrixes lacked either the rows or columns port when:
- the _Input Format_ is _Select Rows/Columns_ 
and
- the number of columns or rows is 1

Before:
![DotMatrix-old](https://user-images.githubusercontent.com/62245695/120902713-283a9080-c642-11eb-9fc4-e66b09dcb026.png)

After:
![DotMatrix-new](https://user-images.githubusercontent.com/62245695/120902720-3ab4ca00-c642-11eb-851e-bfb518d4450a.png)

2021-06-07 06:08 UTC, BFH-ktt1 requested changes
Okay, the pin has been added, but what about the behavior, I do not see how this pin is used in simulation. Could you look into the details (propagate function).
Only adding a single pin does not add all the required functionality.

2021-06-07 07:54 UTC, R3dst0ne commented
There shouldn't be additional functionality needed. It is handled like every other case when _Input Format_ is _Select Rows/Columns_ (setSelect function).
When I tested it, it worked without problems.

2021-06-07 08:12 UTC, R3dst0ne commented
There might be a problem with the [DotMatrixHDLGeneratorFactory](https://github.com/R3dst0ne/logisim-evolution/blob/DotMatrix/src/main/java/com/cburch/logisim/std/io/DotMatrixHDLGeneratorFactory.java). In line 93 is the comment `/* TODO: fix bug when rows == 1 or cols == 1 */`.
I will look into it.

2021-06-10 08:45 UTC, BFH-ktt1 approved these changes

2021-06-10 08:46 UTC, merged