Hitting ESC closes Preferences window now
logisim-evolution/logisim-evolution pull request #645
Opened 2021-06-10 17:46 UTC by MarcinOrlowski

2021-06-11 05:59 UTC, BFH-ktt1 requested changes
Could you remove the System.out.print("Prefs\n"); ?

I'm not sure about the implementation, as there is a special keyhandler object that also assigns functions to for example the escape key. It might interfere, it might not.

2021-06-11 06:14 UTC, MarcinOrlowski commented
`print()` removed.

2021-06-11 13:32 UTC, maehne approved these changes
Thanks @MarcinOrlowski for the contribution! Looks good to me! @BFH-ktt1 do you agree?

2021-06-11 13:34 UTC, maehne commented on src/main/java/com/cburch/logisim/gui/prefs/PreferencesFrame.java
> +import javax.swing.*;
Personally, I prefer that we import only the classes, we actually need.

2021-06-11 13:55 UTC, maehne commented on src/main/java/com/cburch/logisim/gui/prefs/PreferencesFrame.java
> +import javax.swing.*;
Thanks!

2021-06-13 09:21 UTC, MarcinOrlowski commented
Not sure how to make @BFH-ktt1 requested change resolved.

2021-06-13 09:21 UTC, MarcinOrlowski commented
Not sure how to mark @BFH-ktt1 requested change resolved.

2021-06-13 09:59 UTC, maehne approved these changes

2021-06-13 10:08 UTC, maehne commented
Let's merge this. If we should remark later a regression, we can revert it easily.

2021-06-13 10:08 UTC, merged

2021-06-13 11:10 UTC, BFH-ktt1 commented
@maehne : Could you please revert this pull request?
I did not have the time yet to look into the details, but each window has a key-handler. In my earlier implementation for the auto-labler I was not aware yet from this handler and implemented it directly like here as extra handler, causing some keystrokes to mal function (see one of the issues). This is why I did not merge these yet.

2021-06-13 12:14 UTC, MarcinOrlowski commented
@BFH-ktt1 mind pointing to the code that you said you had conflict with previously?