Adds "dirty" marker to window title. Closes #625
logisim-evolution/logisim-evolution pull request #720
Opened 2021-06-24 12:21 UTC by MarcinOrlowski

2021-06-24 20:20 UTC, BFH-ktt1 requested changes
I think it is a typo, but I think you mean 
dirtyMarker and not dirtyNarker, just a detail

2021-06-24 21:04 UTC, MarcinOrlowski commented
Indeed. Fixed. Thanks

2021-06-24 21:05 UTC, MarcinOrlowski reviewed
Typo fixed.

2021-06-25 05:55 UTC, merged

2021-06-30 23:39 UTC, maehne commented on CHANGES.md
> +  * Project "Dirty" state is now also refrected in window title with "*" marker.
Typo: "refrected" -> "reflected"