Documentation changes for V3.5  Library gate
logisim-evolution/logisim-evolution pull request #891
Opened 2021-08-15 19:24 UTC by mbaillif

Many files are modified with the correction of the "Lang" tag.
But the main changes concern the gates library doc.

2021-08-19 13:10 UTC, BFH-ktt1 commented
@mbaillif : When a PR is ready for merge could you please assign a reviewer? After the reviewer say's ok we can merge the PR.

2021-08-19 13:19 UTC, BFH-ktt1 submitted a review, later dismissed

2021-08-19 13:35 UTC, MarcinOrlowski requested changes

2021-08-19 13:35 UTC, MarcinOrlowski commented on src/main/resources/doc/en/html/libs/gates/buffer.html
> +          The output, which always matches the input into the left side. Bit width according to Data  <b class="propertie">Bits attribute</b>.
That's bit odd looking. Shouldn't the "Data Bits" be of class "properties", not just "Bits"?

2021-08-19 13:35 UTC, MarcinOrlowski commented on src/main/resources/doc/en/html/libs/gates/controlled.html
> +          West edge :
No space before punctuation chars, please (**multiple** places).

2021-08-19 13:35 UTC, MarcinOrlowski commented on src/main/resources/doc/libstatus.html
> +		<td align="center" bgcolor="#72BF44"><a href="./en/html/libs/gates/xor.html">__</a></td>
Can we have colors moved to CSS?

2021-08-19 13:36 UTC, MarcinOrlowski commented
I am voiting to block PRs (or automatically rejects them) if too many files are affected. 

If you want to add language to HTML, i.e.:

    <html lang="pt">

then because of the number of files it should go as separate PR.

2021-08-21 19:41 UTC, mbaillif commented
Je vais reprendre tout cela.
Thanks for the comments.

2021-08-21 19:41 UTC, closed without merging

2021-08-25 13:42 UTC, maehne commented
@MarcinOrlowski: I think we should show some tolerance when reviewing PRs from other contributors -- especially if they do their first contributions to the project or, as is the case with @mbaillif, have been continuously maintaining/improving a neglected part of this project, i.e., in this case the documentation. @mbaillif has been contributing improvements to the documentation for several years now, which helped considerable to improve its quality. We should be careful to not frustrate our contributors. Reviewing PRs and pointing out issues, which should be improved is fine as is making suggestions on how to make our and their work easier, e.g., by making topical commits or limiting the scope and size of a PR. Nevertheless, there may be times when it makes sense to propose many changes in one go to consistently rework some aspect of the project. In these cases, we should remind the contributor that it helps if they explain their modifications in the commit messages and/or PR message.

@mbaillif: How would you like to proceed? Can you split the PR with reasonable effort into smaller chunks or do you need someone to review this larger PR? In case of the latter, feel free to reopen this PR and I will try to have a look in the coming days.