Correct behavior of 74161 (make clear async)
logisim-evolution/logisim-evolution pull request #911
Opened 2021-08-22 20:28 UTC by z80jon

The datasheet for the 74161 specifies that clears are supposed to be asynchronous, whereas in the current code it's synchronous. My fix should correct that.

This is my first time touching Logisim code--please forgive me if I've made any mistakes.

2021-08-22 20:30 UTC, z80jon commented
Issue: #910

2021-08-23 20:06 UTC, MarcinOrlowski commented
You mentioned that the current behavior is of 74163 and not for 74161. I've not checked sheets yet, but if that is so, could you please add 7461 so by this PR we could have 74161 and 74163. The code should be pretty much reusable with small exception. Can you please do that, too?

2021-08-23 20:20 UTC, z80jon commented
I'd be happy to! I'm not super familiar with the codebase (and haven't used GitHub a bunch, this is actually my first-ever PR) but I'd definitely be up for it in the next day or two.

Two questions:
-besides a file for the 74163, what else is needed as far as code mods for this PR?
-is there a desire for additional 74xx chips? If the process for adding them isn't too hard (I know there's a bit of graphics work to do, with the internal view tab), I'd definitely be up for making some, as I'm recreating a few for a personal project anyways. How complicated is said process? Is there a 'wish list' of chips I could work on?

I just started using the software a couple days ago (used to use the OG Logisim years ago). Love it and would be happy to contribute a bit here and there.

2021-08-23 20:25 UTC, MarcinOrlowski commented
You may want to take a look at code of other TTL gates we have implemented, as multiple are just the same code base but one difference in flags or so, which looks like what want here.

2021-08-23 20:48 UTC, MarcinOrlowski requested changes

2021-08-23 20:48 UTC, MarcinOrlowski commented on src/main/java/com/cburch/logisim/std/ttl/Ttl74161.java
> +        else if (triggered) {
Please merge this `else if ...` with the `}` line above.

2021-08-25 07:25 UTC, BFH-ktt1 commented
@z80jon : I would propose to move Ttl74161.java to Ttl74163.java and generate a new Ttl74161.java that extends Ttl74163.java with the async clear behavior. I will make a PR for this.

2021-08-25 07:30 UTC, z80jon commented
> @z80jon : I would propose to move Ttl74161.java to Ttl74163.java and generate a new Ttl74161.java that extends Ttl74163.java with the async clear behavior. I will make a PR for this.

That works. I'm going to be a little busy this week, but worry not, I'll take care of it early next week. Also--I'll do some checks to make sure the 74163 meets spec, and do any mods needed for that.

2021-08-25 10:01 UTC, BFH-ktt1 commented
@z80jon : I'm closing this PR as I included it in PR #921

2021-08-25 10:01 UTC, closed without merging

2021-08-25 14:15 UTC, maehne commented
One note @z80jon for the future: Please, make your PRs always against the [`develop` branch](https://github.com/logisim-evolution/logisim-evolution/tree/develop) of Logisim-evolution. The `master` branch contains always the code for the current release version.